### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MarcusTaz** [joelface/bg1#16]
Joel I don't know the details but I have a friend at the parks today WDW, and he's telling me it's not working. Just wanted to bring it to your attention.

**Comment by joelface** [comment]
Do you know what issue they're having? My stats show 20+ people have used it for both Genie+ and the virtual queues today.

**Comment by MarcusTaz** [comment]
Let me ask him specifics and I'll let you know once he gets back to me.

**Comment by MarcusTaz** [comment]
My apologies Joel, apparently it was user error. He did say earlier he was getting a 403 error...

**Comment by divincenzo** [comment]
Omg, heading to the parks next weekend. This is fantastic news thank you Joel… will be sending you a donation shortly!
