### ISSUE TITLE
Getting 404 Error on Virtual Queue

### ISSUE THREAD

**Issue by JosephValle** [joelface/bg1#19]
Followed the steps as directed, have used it before, but today I am getting a page with nothing but this text:

`{"timestamp":"2024-06-18T14:31:04.671+00:00","path":"/vas/","status":404,"error":"Not Found","requestId":"ea52ca9f-1"}`

**Comment by JosephValle** [comment]
I will clarify that this is for the bookmarklet code, and actually, I am getting the same thing for all 4 services (Genie+/VQ for World and Land)

**Comment by JosephValle** [comment]
Just tested on android chrome as well and getting same results

**Comment by joelface** [comment]
Are you sure you're doing the last step under "Using the Bookmarklet" in the setup instructions? You need to run the bookmarket again on that page. In Android Chrome, tap the address bar and type "BG1", then tap BG1 Bookmarklet.

**Comment by JosephValle** [comment]
I think I was doing something wrong, just did it all again and got it. Sorry about that, that's on me.
