### ISSUE TITLE
Attraction starring + search filter?

### ISSUE THREAD

**Issue by mmase** [joelface/bg1#2]
Hi there! Would you be amenable to a PR that adds the ability to star (favorite) attractions (so they always appear at the top of the list) and perhaps a search field that limits results based on a string match?

**Comment by joelface** [comment]
Hi, thanks for the offer! I'll be pushing favoriting and some other tip board changes soon.

I'm going to say no to search, at least for now. MK is the only park that has enough attractions to almost warrant any sort of filtering, and even for it I'm not convinced.

**Comment by mmase** [comment]
Awesome! Makes sense 👍
