### ISSUE TITLE
DAS iPhone Safari

### ISSUE THREAD

**Issue by mhanan99** [joelface/bg1#24]
The DAS button opens a link (to select experience) in Safari and Chrome on my MacBook as well as Chrome on my iPhone. However, it is unresponsive when pressed in Safari on my iPhone.

**Comment by joelface** [comment]
Are you using it in a private tab on your iPhone, by chance? I know that can cause issues with buttons not working in BG1 for reasons that I have yet to track down.

**Comment by mhanan99** [comment]
Yes! That was it. The issue was with the private tab.
