### ISSUE TITLE
Network error at booking 

### ISSUE THREAD

**Issue by MarcusTaz** [joelface/bg1#4]
Seems after last evening when we heard Disney was doing maintenance to their booking system, this morning 8/11 when attempting to book an experience a split second after you select a time an ERROR "Network request failed" pops up appears and then goes away. I have checked my network using both Wi-Fi and mobile both are fine I believe this is an issue worthy of reporting.

**Comment by joelface** [comment]
It looks like there have been some API changes. I don't know the full extent of it yet, but I'll get it fixed as soon as I can. Thanks!

**Comment by MarcusTaz** [comment]
> It looks like there have been some API changes. I don't know the full extent of it yet, but I'll get it fixed as soon as I can. Thanks!

Hey Joel on vacation here, hoping you can get it fixed ASAP. Donation incoming!

**Comment by joelface** [comment]
It should be working now, for the most part. There's still an issue with park hopping. If you try to grab a LL with a next available time before 2 PM and don't have an APR, the API isn't sending back an adjusted time like it did before. MDE seems to failing in the same way, though, so I'm pretty sure this is something that needs to be fixed on Disney's end.

Thanks for the heads-up, and for your generosity!

**Comment by MarcusTaz** [comment]
> It should be working now, for the most part. There's still an issue with park hopping. If you try to grab a LL with a next available time before 2 PM and don't have an APR, the API isn't sending back an adjusted time like it did before. MDE seems to failing in the same way, though, so I'm pretty sure this is something that needs to be fixed on Disney's end.
> 
> Thanks for the heads-up, and for your generosity!

Joel HUGE thank you for getting to it so quickly! Something on Disney's end, it can't be! 😂 And you're very welcome, without this app my experience would be much different and definitely not a positive one!
