### ISSUE TITLE
Lightning Bolt for super late return times

### ISSUE THREAD

**Issue by jerrywilborn** [joelface/bg1#5]
Under rare circumstances, the lightning bolt icon will appear when the criteria aren't met for really late park hours.  For example if it is 6pm and Peter Pan is showing a LL return time of 12:15am (because the park is open until 1AM) and the standby time is 90 minutes, the lightning bolt icon will appear.

**Comment by joelface** [comment]
There are a few places where it assumes the parks aren't open past midnight. I'll fix this soon. Thanks!

**Comment by jerrywilborn** [comment]
❤️

**Comment by joelface** [comment]
I think it'll be a while until the parks are open long enough for this change to be noticeable, but hopefully that takes care of it. Thanks again for the bug report!
