### ISSUE TITLE
What caused LL to be unbookable

### ISSUE THREAD

**Issue by supercoolspy** [joelface/bg1#8]
Title

**Comment by joelface** [comment]
Disney has changed the API for booking/modifying Lightning Lanes. They're using some cryptographic methods to block access from third party clients. I do not expect to have a workaround for this anytime soon, if ever.

**Comment by MarcusTaz** [comment]
Oh NOOOOOOO!!! I'm leaving for vacation in 2 weeks. 😩

**Comment by supercoolspy** [comment]
> Disney has changed the API for booking/modifying Lightning Lanes. They're using some cryptographic methods to block access from third party clients. I do not expect to have a workaround for this anytime soon, if ever.

Do you know what params they added/removed/changed with the API?

**Comment by justindfoley** [comment]
What a bummer... I think I speak for everyone when I say this project has been incredibly beneficial and we appreciate your work! If I had an adequate coding background I would 100% try to help continue development.

**Comment by joelface** [comment]
> Do you know what params they added/removed/changed with the API?

The booking/modification requests now require three new disneyInternalUse0[1-3] parameters.

The issues with working around this aren't just technical (although I believe that part would be nontrivial), but also ethical. To me, Disney is clearly expressing (via code rather than, say, a cease and desist notice) that they don't want third party clients booking LLs. If Disney had contacted me directly and told me to remove that functionality from BG1, I would have of course complied.

I believe that respecting their wishes is the right thing to do, no matter how much I'd like to continue providing a better Genie+ experience than Disney themselves is currently able to.

**Comment by MarcusTaz** [comment]
Joel has Disney ever contacted you regarding your work?

**Comment by joelface** [comment]
> Joel has Disney ever contacted you regarding your work?

Nope

**Comment by joeyman178** [comment]
> > Joel has Disney ever contacted you regarding your work?
> 
> 
> 
> Nope

Is there any tips on efficiently booking lightning lane rides now? Trip is in three days. Typical!

**Comment by joelface** [comment]
> Is there any tips on efficiently booking lightning lane rides now?

Only one I can think of at the moment: Use the Edit Selections feature on the tip board to keep the attraction(s) you want to book next pinned to the top. I don't think you can see that feature until after purchasing Genie+, but there are YouTube videos that show it.

**Comment by supercoolspy** [comment]
> > Is there any tips on efficiently booking lightning lane rides now?
> 
> Only one I can think of at the moment: Use the Edit Selections feature on the tip board to keep the attraction(s) you want to book next pinned to the top. I don't think you can see that feature until after purchasing Genie+, but there are YouTube videos that show it.

Doesn't [Thrill Data](https://www.thrill-data.com/) have an alerts service for the lighting lane?

**Comment by MarcusTaz** [comment]
> > Is there any tips on efficiently booking lightning lane rides now?
> 
> Only one I can think of at the moment: Use the Edit Selections feature on the tip board to keep the attraction(s) you want to book next pinned to the top. I don't think you can see that feature until after purchasing Genie+, but there are YouTube videos that show it.

Joel the drop times are still a fixed time or do they vary? Another words I'm wondering about using your interface to keep my eye on things and then of course jump over to the official app to try to book.

**Comment by joelface** [comment]
The drop times haven't changed AFAIK. You can still use BG1 to monitor return times, and then just switch to MDE for booking/modifying. The Genie+ button on the BG1 start page has been renamed to DAS / Times (I'm probably going to tweak that again, since some people think it can only be used for DAS now), but it's all still there.

**Comment by MarcusTaz** [comment]
Good to know Joel thank you!

**Comment by alexpleszko** [comment]
Hey Joel, congrats for the work so far. I would like very much to contribute by coding but it is not my specialty, however would be willing to donate. Are you trying to fix the LL booking or gave up? My trip will be just in January, I hope I can find something until then... Thanks

**Comment by 0x-2a** [comment]
Hrm does anyone know how the standby skipper app seems to be able to still book LLs? https://www.standbyskipper.com/faq#h.h55brjgfwe44

I can't seem to find any technical detail on the app and am left to speculate that they might be using an authenticated web session by being an added family member on MDE?

**Comment by joelface** [comment]
Last I knew, Standby Skipper does involve (temporarily) linking accounts thru MDE, but they still have to send the required `disneyInternalUse` params for LL booking/modifying requests.

**Comment by chrismartin8080** [comment]
Do you have any insights on how Standby Skipper managed to generate the `DisneyInternalUse` parameters? I attempted to decompile the MDE Android app, but it appears that due to obfuscation, pinpointing the method of generation isn't straightforward.

**Comment by joelface** [comment]
> Do you have any insights on how Standby Skipper managed to generate the `DisneyInternalUse` parameters?

No, sorry. Just some smart reverse engineering, I assume.

**Comment by joelface** [comment]
I've had a change of heart and have implemented the code necessary to book/modify LLs again. The unobfuscated source code for this is in a private repo and will probably remain there for the foreseeable future. Thanks, all!

**Comment by MarcusTaz** [comment]
> I've had a change of heart and have implemented the code necessary to book/modify LLs again. The unobfuscated source code for this is in a private repo and will probably remain there for the foreseeable future. Thanks, all!

Well bless your heart Joe!!!

**Comment by supercoolspy** [comment]
> I've had a change of heart and have implemented the code necessary to book/modify LLs again. The unobfuscated source code for this is in a private repo and will probably remain there for the foreseeable future.

Will we be able to book them with the bookmark and wouldn't that be a gpl licence violation? As you have to disclose the source

(Not legal advice)

**Comment by joelface** [comment]
> Will we be able to book them with the bookmark

Yes, of course.

> wouldn't that be a gpl licence violation? As you have to disclose the source

The GPL (or any copyright license) doesn't apply to the copyright holder, [who would be the one with the power to enforce the license anyway](https://www.gnu.org/licenses/gpl-faq.html#WhoHasThePower).

**Comment by supercoolspy** [comment]
> > Will we be able to book them with the bookmark
> 
> Yes, of course.
> 
> > wouldn't that be a gpl licence violation? As you have to disclose the source
> 
> The GPL (or any copyright license) doesn't apply to the copyright holder, [who would be the one with the power to enforce the license anyway](https://www.gnu.org/licenses/gpl-faq.html#WhoHasThePower).

Oh alright thanks for the clarification
